-- ==========================================
-- RESET DATABASE (FOR DEVELOPMENT)
-- Drop tables in reverse dependency order
-- ==========================================

DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS system_logs CASCADE;
DROP TABLE IF EXISTS organization_documents CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;


DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS organization_members CASCADE;

DROP TABLE IF EXISTS registrations CASCADE;

DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS activity_categories CASCADE;

DROP TABLE IF EXISTS organizations CASCADE;

DROP TABLE IF EXISTS users CASCADE;
-- ==========================================
-- TABLES (IDs generated by Backend and stored as VARCHAR)
-- Note: Column names use double quotes to preserve case
-- ==========================================

-- USERS
CREATE TABLE users (
    "userId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,-- userId is auto-incremented
    "userName" VARCHAR(255) NOT NULL,
    "studentId" VARCHAR(50),
    "university" VARCHAR(255) NOT NULL,

    "phoneNumber" VARCHAR(20) UNIQUE,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,

    "status" VARCHAR(20) DEFAULT 'active'
        CHECK ("status" IN ('active','inactive','banned','suspended')),

    "avatarUrl" TEXT,

    -- audit
    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId"),

    UNIQUE("studentId","university")
);
-- ORGANIZATIONS
CREATE TABLE organizations (
    "organizationId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "organizationName" VARCHAR(255) NOT NULL,
    "organizationType" VARCHAR(50) NOT NULL
        CHECK ("organizationType" IN ('university','club','department','company')),

    "logoUrl" TEXT,
    "coverImageUrl" TEXT,
    "description" TEXT,

    -- audit
    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);
-- ORGANIZATION MEMBERS
CREATE TABLE organization_members (
    "userId" INT REFERENCES users("userId"),
    "organizationId" INT REFERENCES organizations("organizationId"),

    "role" VARCHAR(50)
        CHECK ("role" IN ('member','admin','leader')),
    "joinDate" DATE,

    PRIMARY KEY ("userId", "organizationId"),

    -- audit
    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);
-- ACTIVITY CATEGORIES
CREATE TABLE activity_categories (
    "categoryId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "categoryName" VARCHAR(255) UNIQUE NOT NULL,

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

-- ACTIVITIES
CREATE TABLE activities (
    "activityId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "activityName" VARCHAR(255) NOT NULL,
    "location" VARCHAR(255),
    "activityType" VARCHAR(50) NOT NULL
        CHECK ("activityType" IN ('event','competition','workshop','seminar')),

    "startTime" TIMESTAMP,
    "endTime" TIMESTAMP ,
      CONSTRAINT check_activity_time
      CHECK ("endTime" IS NULL OR "endTime" > "startTime"),
    "registrationDeadline" TIMESTAMP,
    CHECK (
    "registrationDeadline" IS NULL
    OR "startTime" IS NULL
    OR "registrationDeadline" <= "startTime"
),
    "maxParticipants" INT,
    "minParticipants" INT,
    CHECK (
    "maxParticipants" IS NULL 
    OR "minParticipants" IS NULL
    OR "maxParticipants" >= "minParticipants"
),
    "groupRegistration" BOOLEAN DEFAULT FALSE,

    "approvalStatus" VARCHAR(50) DEFAULT 'pending'
        CHECK ("approvalStatus" IN ('pending','approved','rejected')),
    "prize" TEXT,

    "coverImage" TEXT,
    "description" TEXT,

    "organizationId" INT NOT NULL REFERENCES organizations("organizationId"),
    "categoryId" INT NOT NULL REFERENCES activity_categories("categoryId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

-- REGISTRATION FORMS
CREATE TABLE registrations (
    "registrationId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "status" VARCHAR(50) DEFAULT 'pending'
        CHECK ("status" IN ('pending','approved','rejected','cancelled')),

    "registrationTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    "registrationType" VARCHAR(50) DEFAULT 'individual'
        CHECK ("registrationType" IN ('individual','group')),
    "checkInTime" TIMESTAMP,
    "checkOutTime" TIMESTAMP,

    "userId" INT NOT NULL REFERENCES users("userId"),
    "activityId" INT NOT NULL REFERENCES activities("activityId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId"),
    UNIQUE("userId","activityId")
);


-- TEAM MEMBERS
CREATE TABLE team_members (
    "registrationId" INT NOT NULL REFERENCES registrations("registrationId"),
    "userId" INT NOT NULL REFERENCES users("userId"),

    "role" VARCHAR(50)
        CHECK ("role" IN ('leader','member')),

    PRIMARY KEY ("registrationId","userId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);



-- REVIEWS
CREATE TABLE reviews (
    "reviewId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "rating" INT NOT NULL CHECK ("rating" BETWEEN 1 AND 5),
    "comment" TEXT,
    "reviewTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    "registrationId" INT UNIQUE NOT NULL
        REFERENCES registrations("registrationId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);



-- ORGANIZATION DOCUMENTS
CREATE TABLE organization_documents (
    "documentId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "documentName" VARCHAR(255) NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "category" VARCHAR(50),

    "organizationId" INT NOT NULL REFERENCES organizations("organizationId"),
    "userId" INT NOT NULL REFERENCES users("userId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

-- SYSTEM LOGS
CREATE TABLE system_logs (
    "logId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "action" VARCHAR(255),
    "executionTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "oldData" TEXT,
    "newData" TEXT,

    "userId" INT NOT NULL REFERENCES users("userId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

-- NOTIFICATIONS
CREATE TABLE notifications (
    "notificationId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "title" VARCHAR(255) NOT NULL,
    "content" TEXT,
    "notificationTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    "status" VARCHAR(50) DEFAULT 'unread'
        CHECK ("status" IN ('unread','read')),

    "notificationType" VARCHAR(50)
        CHECK ("notificationType" IN ('activity','registration','system')),

    "userId" INT NOT NULL REFERENCES users("userId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);
-- ROLES
CREATE TABLE roles (
    "roleId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "code" VARCHAR(50) UNIQUE NOT NULL
        CHECK ("code" IN (
            'admin',
            'student',
            'organization_leader',
            'organization_member'
        )),

    "roleName" VARCHAR(255) UNIQUE NOT NULL,
    "description" TEXT,

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);
-- USER ROLES
CREATE TABLE user_roles (
    "userId" INT NOT NULL REFERENCES users("userId"),
    "roleId" INT NOT NULL REFERENCES roles("roleId"),

    PRIMARY KEY ("userId","roleId"),

    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);
CREATE TABLE club_recruitment_rounds (
    "roundId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "roundName" VARCHAR(255) NOT NULL,
    "description" TEXT,

    "startDate" DATE,
    "endDate" DATE,

    "status" VARCHAR(20) NOT NULL
        CHECK ("status" IN ('draft','open','closed','cancelled'))
        DEFAULT 'draft',

    "organizationId" INT NOT NULL
REFERENCES organizations("organizationId"),

    CHECK (
    "endDate" IS NULL 
    OR "startDate" IS NULL 
    OR "endDate" >= "startDate"
),

    -- Audit fields
    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

CREATE TABLE club_application_forms (
    "applicationId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    "interviewAnswers" TEXT,

    "submittedDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "interviewSchedule" TIMESTAMP,
    CHECK (
    "interviewSchedule" IS NULL
    OR "submittedDate" IS NULL
    OR "interviewSchedule" >= "submittedDate"
),
    "interviewResult" VARCHAR(20)
        CHECK ("interviewResult" IN ('pending','passed','failed'))
        DEFAULT 'pending',

    "notes" TEXT,

    "roundId" INT NOT NULL
        REFERENCES club_recruitment_rounds("roundId"),

    "userId" INT NOT NULL
        REFERENCES users("userId"),

    UNIQUE ("userId","roundId"),

-- Audit fields
    "isDeleted" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,

    "createdBy" INT REFERENCES users("userId"),
    "updatedBy" INT REFERENCES users("userId"),
    "deletedBy" INT REFERENCES users("userId")
);

--Create index
-- ==========================================
-- INDEXES (Performance Optimization)
-- ==========================================

-- USERS
-- login / search user
CREATE INDEX idx_users_email
ON users("email");

CREATE INDEX idx_users_student
ON users("studentId","university");


-- ORGANIZATION MEMBERS
-- get members of organization
CREATE INDEX idx_org_members_organization
ON organization_members("organizationId");

-- get organizations of user
CREATE INDEX idx_org_members_user
ON organization_members("userId");


-- ACTIVITIES
-- get activities of organization
CREATE INDEX idx_activities_organization
ON activities("organizationId");

-- get activities by category
CREATE INDEX idx_activities_category
ON activities("categoryId");


-- REGISTRATIONS
-- get registrations of activity
CREATE INDEX idx_registrations_activity
ON registrations("activityId");

-- get activities a user registered
CREATE INDEX idx_registrations_user
ON registrations("userId");


-- TEAM MEMBERS
-- get team members of registration
CREATE INDEX idx_team_members_registration
ON team_members("registrationId");

-- get teams of user
CREATE INDEX idx_team_members_user
ON team_members("userId");


-- NOTIFICATIONS
-- get notifications of user
CREATE INDEX idx_notifications_user
ON notifications("userId");

-- sort notifications
CREATE INDEX idx_notifications_user_time
ON notifications("userId","notificationTime" DESC);


-- SYSTEM LOGS
-- get logs by user
CREATE INDEX idx_system_logs_user
ON system_logs("userId");
-- club_recruitment_rounds
CREATE INDEX idx_application_round
ON club_application_forms("roundId");

CREATE INDEX idx_application_user
ON club_application_forms("userId");